#+TITLE: article
#+DATE: 2017-04-05
#+LAYOUT: post
#+TAGS: PLT
#+CATEGORIES: PLT

* 基本知识的储备
  - lambda 演算的理解
  - 形式系统
  - 排中律：$(\neg P \lor P)$ 对于任何命题$P$都为真。
  - 连续统假设
  - 数论：數論是纯粹数学的分支之一，主要研究整数的性質
  - 悖论：同一命题或推理中隐含两个对立的结论
  - 消除自指结构是不可能的因为还有间接的自指。
  - 无偿提供的定理叫公理
* TODO 形式系统
  一个形式系统由两部分组成，形式语言和推理规则。形式语言包含简单的符号（或者说lexeme）以及语法（文法），换句话说，形式系统有符号表上某些有限长的符号串（语句）的集合构成。基础公理可以认为是符合语法的简单语句。有一点要注意的是，符合语法的符号串才是形式语言的一部分。在计算机科学中我们称这些语句为表达式
** TODO 涉及的形式系统的类型
   - 一阶逻辑
** 矛盾和一致性
* lambda 演算
  在提到函数式编程的时候，不免要提到lambda演算。是一套用于研究函数定义、函数应用和递归的形式系统，所以只要看它的组件即可理解。形式语言的符号一般使用英文字母以及某些单词，作为最小的编程语言，内置了运算的符号也应加入。
、达式都是函数，所以形式语言是函数的集合。
* 康托的对角线方法
  对于无穷集合的大小，无法用数目来衡量，所以引入了一一对应来实现
* 符号系统
  由简单到复杂来学习形式系统  
* 逻辑Agent
* 哥德尔不完备性定理和其证明的价值
* 编译和符号系统的关系
  符号系统最基本的是符号，对应的自然是token或者说lexeme
* TODO 问题
** TODO 形式系统中，不可判定的问题比可判定的问题要多
** TODO 现实一切都可以用形式系统表示吗？
   如果宇宙是以确定方式运动则可能，则可能
* 布尔巴基
* TODO 论文目标
  - [ ] 非形式证明哥德尔的不完备性定理
* 思考
  - 形式系统最重要的是形式
  - 形式系统的复杂度是如何提高的是一个问题
  - 类型系统应该是包含属于语义
  - 接口可以分为两种，一种是作用于状态的接口，必须同时了解接口和接口对资源或者状态的操作。另一种着重了解接口的输入和输出
  - 语义的赋予
  - 抽象的能力是智能的关键，自指
  - 数学理论的解释，先出理论基础在编写
  - 可证的概念至少要在一个形式系统中才有意义
  - 证明就形式上来说是由推理规则联系的一个个符合语法的命题
  - 生成规则和推理规则没有本质区别
* 零散
  - 语义的赋予称为解释
  - 循环就是以有穷的方式描述无休止过程的方法
* FAQ
** 形式系统和形式语言的关系？
   形式语言是形式系统的一部分，加上一个推理规则便成了形式系统。即
** TODO 传统数学中令人误解的函数语义
** 形式语言是否是基本公理的
** 数学领域的符号系统是什么？
   数学中抽象是最为重要的，为了抽象出对象的特性，对于不同的研究对象我们时常要构造一个形式系统，但不同分支的数学家门在使用符号上却比较随便，在其他人造成了很大的困扰。
** 程序设计语言是否是一个形式系统？
** 公理系统、数学理论和形式系统的关系？
   公理系统是公理的集合，而数学理论则是由公理系统和以此为基础逻辑逻辑地导出的定理组成。一个完全描述出来的公理系统是形式系统的特例。实际上，多数数学理论的公理系统都是半形式化描述的。这样更易于理解。
** 自洽、一致性、相同性？
   都是consisency的翻译，指在一个形式系统中不存在矛盾。
** 一个公理化的数学系统，如何证明其无矛盾？
所谓无矛盾性证明，其实都是指相对无矛盾。也就是说你必须假定一些最基本的公理系统（比如皮亚诺公理系统，ZFC公理系统）的无矛盾性，然后才能得到其它系统的无矛盾性。在假定这些最基本公理系统的无矛盾性下，针对其它公理系统，有语法和语义两种方法证明无矛盾性。语法方法被称为证明论，语义方法被称为模型论。其具体描述如下：1）证明论方法：主要是通过cut-elimination的纯语法方法得到，这需要假定一些大的序数的存在性作为前提。比如比亚诺算术的无矛盾性可以通过语法方法在假定存在的情况下得到（即著名的Gentzen方法）。这种方法的缺点是繁琐，威力有限。一般只用于处理比较基本的公理系统。2）模型论方法: 就是通过构造模型来证明无矛盾性，其原理是哥德尔完备性定理。比如著名连续统假设的协调性就是通过构造模型证明的。这种方法非常强有力，被广泛应用于集合论，比如力迫法，内模型法都是构造模型的方法。但是必须指出由于哥德尔不完备性定理，很多命题的协调性在只假定基本公理系统的前提是不能被证明的。因此寻求“合理的”公理系统就成为集合论学家们一项重要任务。比如各种大基数公理就是集合论学家试图证明一些非常自然的数学命题的协调性而得到的。

作者：匿名用户
链接：https://www.zhihu.com/question/30564202/answer/48549344
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
** TODO 公理系统的一致性的语法和语义的证明
* 参考文献
  - http://mp.weixin.qq.com/s?__biz=MzIwMDgyNzUzNw==&mid=2247483658&idx=1&sn=2dde89033d2fef0cba307db9b8b5489e&scene=0#wechat_redirect
  - [[https://zh.wikipedia.org/wiki/%E5%BD%A2%E5%BC%8F%E7%B3%BB%E7%B5%B1][形式系统]]
  - [[https://zh.wikipedia.org/wiki/%E5%85%AC%E7%90%86%E7%B3%BB%E7%BB%9F][公理系统]]
  - [[https://zh.wikipedia.org/wiki/%E4%B8%80%E8%87%B4%E6%80%A7_(%E9%82%8F%E8%BC%AF)][一致性]]
  - [[https://zh.wikipedia.org/wiki/%E5%93%A5%E5%BE%B7%E5%B0%94%E5%AE%8C%E5%A4%87%E6%80%A7%E5%AE%9A%E7%90%86][哥德尔完备性定理]]
  - [[https://zh.wikipedia.org/wiki/%E4%B8%80%E9%98%B6%E9%80%BB%E8%BE%91][一阶逻辑wiki]]
